// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-xmdG9YfNoerqwUldwiHanjLjziY-084',
    appId: '1:675386171417:web:08a3158e9241d8b4b00a88',
    messagingSenderId: '675386171417',
    projectId: 'flutter-payup',
    authDomain: 'flutter-payup.firebaseapp.com',
    storageBucket: 'flutter-payup.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-w7240nDdH1pezYelFrVrHpYQimvS7x8',
    appId: '1:675386171417:android:0f00c7204a27a0fab00a88',
    messagingSenderId: '675386171417',
    projectId: 'flutter-payup',
    storageBucket: 'flutter-payup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0q57gai-6NxQC9_6hwBufkbAdPxGMZBM',
    appId: '1:675386171417:ios:61b0dd736dc17aeab00a88',
    messagingSenderId: '675386171417',
    projectId: 'flutter-payup',
    storageBucket: 'flutter-payup.firebasestorage.app',
    iosBundleId: 'com.example.payup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0q57gai-6NxQC9_6hwBufkbAdPxGMZBM',
    appId: '1:675386171417:ios:61b0dd736dc17aeab00a88',
    messagingSenderId: '675386171417',
    projectId: 'flutter-payup',
    storageBucket: 'flutter-payup.firebasestorage.app',
    iosBundleId: 'com.example.payup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-xmdG9YfNoerqwUldwiHanjLjziY-084',
    appId: '1:675386171417:web:1e93fe169af871eab00a88',
    messagingSenderId: '675386171417',
    projectId: 'flutter-payup',
    authDomain: 'flutter-payup.firebaseapp.com',
    storageBucket: 'flutter-payup.firebasestorage.app',
  );

}